<?php
/**
 *  jumpage Your web concept Framework
 *  Copyright (C) 2012 Bureau BLEEN Design Development
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see http://www.gnu.org/licenses.
 *  
 *  @author Ralf Langebrake
 *  @link jumpage.net
 *
 *  Install the jumpage Facebook App and get your strong Page Access
 *  Token on jumpage.net/app
 *  
 */
?><!DOCTYPE html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"><![endif]-->
<!--[if IE 7 ]><html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]><html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en" class="no-js"><!--<![endif]-->
<head prefix="og: http://ogp.me/ns#">
<meta charset="UTF-8" />
<title><?= $this->getField('name', 'New jumpage at work') ?></title>
<?= $this->getField('about', '', '<meta name="description" content="', '" />') ?>

<meta name="generator" content="<?= $this->version ?>" />
<meta property="og:title" content="<?= $this->getField('name') ?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?= 'http://' . $url . '/' ?>" />
<meta property="og:image" content="<?= 'http://' . $url . '/facebook-link-icon.jpg' ?>" />
<?= $this->getField('about', '', '<meta property="og:description" content="', '" />') ?>

<link rel="apple-touch-icon" href="<?= 'http://' . $url . '/apple-touch-icon.png' ?>" />
<link rel="image_src" href="<?= 'http://' . $url . '/facebook-link-icon.jpg' ?>" />
<link rel="shortcut icon" href="<?= 'http://' . $url . '/favicon.ico' ?>" />
<link rel="stylesheet" href="common/jumpage.css" />
<!--[if lt IE 9]><script src="common/modernizr-2.5.3.min.js"></script><![endif]-->
</head>
<body>

<header></header>

<?= $this->getField('about', '', '<section class="decription">', '"</section>') ?>

<section class="images">
<?php foreach($this->images as $image) { ?>
<div class="image"></div>
<?php } ?>
</section>

<section class="posts">
<?php foreach($this->posts as $post) { ?>
<div class="post"></div>
<?php } ?>
</section>

<section class="events"></section>

<!--section class="maps"><div id="map"></div></section-->

<footer></footer>

<!--
This website was built with jumpage Your web concept - A Bureau BLEEN project
For more information and how to use it, visit jumpage.net
-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>

<script>!window.jQuery && document.write(unescape(
'%3Cscript src="common/jquery-1.8.0.min.js"%3E%3C/script%3E'));</script>

<!--script src="//maps.google.com/maps/api/js?sensor=false"></script-->

<script src="common/jumpage.js"></script>

<!--script>
var _gaq = [['_setAccount', 'UA-XXXXXXXX-X'], ['_gat._anonymizeIp'], ['_trackPageview']];
(function(d, t){
	var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
	g.async = true;
	g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www')
	+ '.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g, s);
})(document, 'script');
</script-->

</body>
</html>