<?php
/**
 *  jumpage Framework
 *  Copyright (C) 2012-2013 Bureau BLEEN OHG
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see http://www.gnu.org/licenses.
 *  
 *  @author Ralf Langebrake
 *  @link jumpage.net
 *
 *  Install the jumpage Facebook App and get your strong Page Access
 *  Token on jumpage.net/app
 *  
 */
?><?php 

$showGoogleMaps = strlen(trim($this->getField('zip'))) > 0;

?><!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"><!--<![endif]-->
<head prefix="og: http://ogp.me/ns#">
<meta charset="UTF-8" />
<title><?= $this->getField('name', 'New jumpage at work') ?></title>
<?= $this->getField('about', '', '<meta name="description" content="', '" />') ?>

<meta name="generator" content="<?= $this->version ?>" />
<meta name="apple-mobile-web-app-capable" content="yes" />

<meta property="og:title" content="<?= $this->getField('name') ?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?= 'http://' . $this->baseurl . '/'  ?>" />
<meta property="og:image" content="<?= 'http://' . $this->baseurl . '/open-graph-icon.jpg' ?>" />
<?= $this->getField('about', '', '<meta property="og:description" content="', '" />') ?>

<link rel="apple-touch-icon" href="<?= 'http://' . $this->baseurl . '/apple-touch-icon.png' ?>" />
<link rel="image_src" href="<?= 'http://' . $this->baseurl . '/open-graph-icon.jpg' ?>" />
<link rel="shortcut icon" href="<?= 'http://' . $this->baseurl . '/favicon.ico' ?>" />

<link rel="stylesheet" href="common/jumpage.css" />

<script src="common/modernizr-2.6.2.min.js"></script>

<base target="_top" />

</head>
<body>

<header>
<div class="pagetitle">
<?= $this->getField('name', '', '<h1 class="t-large">', '</h1>') ?>
<?= $this->getField('categories', '', '<h2>', '</h2>') ?>
</div>
<?php if($cover = @$this->getImage($this->profile['cover']->cover_id)) { ?>
<figure class="cover"><img 
class="ir fit" src="<?= $cover->src 
?>" width="<?= $cover->width 
?>" height="<?= $cover->height 
?>" alt="<?= $cover->alt 
?>" />
<?= $this->getField('about', '', '<figcaption class="txpdt"><p class="t-medium">', '</p></figcaption>') ?>
</figure>
<?php } else { ?>
<?= $this->getField('about', '', '<div class="txpdt"><p class="t-medium">', '</p></div>') ?>
<?php } ?>
</header>

<?php if(count($this->posts) > 0) { ?>
<section class="wall">
<?php $hasImage = false; foreach($this->posts as $post) { ?>
<div class="post"><?php if($post->image !== false) { 
?><?php if($post->image->type == 'image' || $post->image->type == 'video') { $hasImage = true;
?><a href="<?= htmlentities($post->href) 
?>"><img class="fit<?= $post->image->type == 'video' ? ' ' . $post->image->origin . ' video' : '' 
?>" src="<?= $post->image->src 
?>" width="<?= $post->image->width 
?>" height="<?= $post->image->height 
?>" alt="" /></a><?php } ?><?php } ?><?php if($post->message !== '') { 
?><div class="txpdg bg-light"><p class=" t-small">
<?= $post->message ?> <a href="<?= htmlentities($post->href) 
?>"><?= $this->localize('MoreOnFacebook') ?></a></p></div><?php } ?></div>
<?php } ?>
<div class="clr"></div>
</section>
<?php } ?>

<div class="noprint followbtn"><a href="<?= $this->getField('link') 
?>" class="btn t-medium c-light"><?= $this->localize('Follow') 
?> <?=  $this->getField('name') 
?> <?= $this->localize('onFacebook') 
?></a></div>

<?= $this->getField('description', '', '<section><div class="rsp ptz"><p class="t-medium">', '</p></div></section>', true) ?>

<footer>
<?php if($showGoogleMaps) { ?>
<div id="google_maps"></div>
<?php } ?>
<?php 
$website = trim($this->getField('website'));
if($website == '')
{
	$website = '<span class="org bold">' . $this->getField('name') . '</span>';	
}
else
{
	$website = '<a title="' 
 		. $this->getField('name') 
		.'" class="url org bold" href="http://' 
 		. str_replace('http://', '', $this->getField('website')) 
		. '" rel="bookmark">'
 		. $this->getField('name')
		. '</a>';
}
?>
<div class="cntr plr">
<div class="tbl"><div class="row">
<div class="col txpdt vcard pdr" id="hcard">
<div class="t-medium c-light"><?= $website ?>
<div class="adr">
<?= $this->getField('street', '', '<span class="street-address">', '</span><br />') 
?> <?= $this->getField('zip', '', '<span class="postal-code">', '</span>') 
?> <?= $this->getField('city', '', '<span class="locality">', '</span>')
?> <?= $this->getField('country', '', '<span class="country-name">', '</span>')
?>
</div>
<div class="pdt">
	<?= $this->getField('phone', '', '<span class="tel"><span class="type">Work</span> <span class="type">Voice</span> T <span class="value" title="', '">') 
	?><?= $this->getField('phone', '', '', '</span></span>') ?>
</div>
</div></div>
<div class="col txpdt pdl"><div class="t-medium c-light">

<?php $openingTimes = $this->getOpeningTimes(); if(count($openingTimes['time']) > 0){ ?>
<?= $this->localize('OpeningTimes') ?><br />
<?php

$myTimes = array();

foreach ($openingTimes['time'] as $openingTime)
{
	$bits = explode('|', $openingTime);
	$days = explode(', ', $bits[0]);
	
	$time = $bits[1];
	$day = '';
 	
	$i = count($days);
	
	if ($i == 2)
	{
		$day = implode('/', $days);
	}
	elseif ($i > 2)
	{
		$day = array_shift($days);
		$day .= ' - ' . array_pop($days);
	}
	else
	{
		$day = $days[0];
	}
	
	$myTimes[] = str_replace(array(
		'mon',
		'tue',
		'wed',
		'thu',
		'fri',
		'sat',
		'sun'
	), array(
		$this->localize('mon'),
		$this->localize('tue'),
		$this->localize('wed'),
		$this->localize('thu'),
		$this->localize('fri'),
		$this->localize('sat'),
		$this->localize('sun')
	), $day) . ' ' . str_replace(array(
		':00',
		'-'
	  ), array(
		':00',
		' - '
	  ), $time) . '';
}
?>
<?php foreach($myTimes as $myTime) { ?>
<?= $myTime ?><br />
<?php } ?>
<?php } ?>

</div></div>
</div>
</div>

<?php
if(!empty($this->_cfg->notes['legal']) && is_numeric($this->_cfg->notes['legal']))
{
if($legal =  $this->getNote($this->_cfg->notes['legal'], true, true))
{
$legal_subject = $legal->subject;
$legal_message = $this->linkify($legal->message);
?>
<div class="rsp"><p class="t-small c-light"><?= $legal_message ?></p></div>
<?php }} ?>
</div>
</footer>

<!--
This website was built with jumpage Your web concept - A Bureau BLEEN project
For more information and how to use it, visit jumpage.net
-->

<div class="buttonbar noprint">
<div class="cntr buttons"><a class="pdr" title="<?= $this->localize('Follow') ?> <?=  $this->getField('name') 
?> <?= $this->localize('onFacebook') ?>" href="<?= $this->getField('link') ?>"><img 
class="hvr" src="common/facebook.png" width="48" height="48" alt="Facebook" /></a><a 
class="pdl" title="<?= $this->localize('JumpageWebsiteTitle') 
?>" href="http://<?= $this->localize('JumpageWebsiteUrl') ?>/"><img class="hvr"
src="common/jumpage.png" width="48" height="48" alt="jumpage" /></a><div class="topbtn"><a 
href="#top"><img class="hvr" src="common/up.png" width="48" height="48" alt="Up" /></a></div>
</div></div><div class="mobile"></div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php if($showGoogleMaps) { ?>
<script src="//maps.google.com/maps/api/js?sensor=false"></script>
<?php } ?>
<script>!window.jQuery && document.write(unescape('%3Cscript '
+ 'src="common/jquery-1.9.1.min.js"%3E%3C/script%3E'));</script><script>
var googleMapsConfig = [];
googleMapsConfig['Lat'] = <?= floatval($this->getField('latitude')) ?>;
googleMapsConfig['Lng'] = <?= floatval($this->getField('longitude')) ?>;
googleMapsConfig['address'] = '<?= urlencode($this->getField('street')) . ',' 
	. $this->getField('zip') . ',' . urlencode($this->getField('city')) ?>';
googleMapsConfig['href'] = '<?= $this->_cfg->googlePlacesLink ?>';
googleMapsConfig['title'] = 'Route planen mit Google Maps...';
googleMapsConfig['zoom'] = 15;
</script>

<script src="common/jumpage.js"></script>
<?php if(!empty($this->_cfg->googleAnalyticsWebpropertyId)) { ?>
<script>
var _gaq = [['_setAccount', '<?= $this->_cfg->googleAnalyticsWebpropertyId ?>'], ['_gat._anonymizeIp'], ['_trackPageview']];
(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
<?php } ?>

</body>
</html>