<?php
/**
 *  jumpage Your web concept Framework
 *  Copyright (C) 2012 Bureau BLEEN Design Development
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see http://www.gnu.org/licenses.
 *  
 *  @author Ralf Langebrake
 *  @link jumpage.net
 *
 *  Install the jumpage Facebook App and get your strong Page Access
 *  Token on jumpage.net/app
 *  
 */
?><?php 

$showGoogleMaps = strlen(trim($this->getField('zip'))) > 0;

?><!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"><!--<![endif]-->
<head prefix="og: http://ogp.me/ns#">
<meta charset="UTF-8" />
<title><?= $this->getField('name', 'New jumpage at work') ?></title>
<?= $this->getField('about', '', '<meta name="description" content="', '" />') ?>


<meta name="generator" content="<?= $this->version ?>" />

<meta property="og:title" content="<?= $this->getField('name') ?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?= 'http://' . $this->baseurl . '/' ?>" />
<meta property="og:image" content="<?= 'http://' . $this->baseurl . '/open-graph-icon.jpg' ?>" />
<?= $this->getField('about', '', '<meta property="og:description" content="', '" />') ?>

<link rel="apple-touch-icon" href="<?= 'http://' . $this->baseurl . '/apple-touch-icon.png' ?>" />
<link rel="image_src" href="<?= 'http://' . $this->baseurl . '/open-graph-icon.jpg' ?>" />
<link rel="shortcut icon" href="<?= 'http://' . $this->baseurl . '/favicon.ico' ?>" />
<link rel="stylesheet" href="common/jumpage.css" />
<script src="common/modernizr-2.6.2.min.js"></script>
</head>
<body>
<!--[if lt IE 7]><p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p><![endif]-->

<header>
<div class="rsp">
<?= $this->getField('name', '', '<h1 class="t-large">', '</h1>') ?>
<?= $this->getField('categories', '', '<h2 class="t-large c-dark">', '</h2>') ?>
<?php if($cover = $this->getImage($this->profile['cover']->cover_id)) { ?>
</div>
<figure class="rsp cover"><img 
class="ir fit" src="<?= $cover->src 
?>" width="<?= $cover->width 
?>" height="<?= $cover->height 
?>" alt="<?= $cover->alt 
?>" />
<?= $this->getField('about', '', '<figcaption class="pdt"><p class="t-medium">', '</p></figcaption>') ?>
</figure>
<?php } else { ?>
<?= $this->getField('about', '', '<div class="pdt"><p class="t-medium">', '</p></div>') ?>
<?php } ?>
</header>

<?php if(count($this->posts) > 0) { ?>
<section class="wall">
<div class="tbl">
<div class="row">
<div class="col">
<?php foreach($this->posts as $post) { if($post->colnum == 0) { ?>
<div class="spacer mgr">
<?php if($post->image !== false) { ?>
<?php if($post->image->type == 'image') { ?>
<div class="postimg">
<a href="<?= htmlentities($post->href) 
?>"><img class="fit" src="<?= $post->image->src 
?>" width="<?= $post->image->width 
?>" height="<?= $post->image->height 
?>" alt="" /></a></div>
<?php } elseif($post->image->type == 'video') { ?>
<div class="postvideo"><?= $post->image->html ?></div>
<?php } ?>
<?php } ?>
<?php if($post->message !== '') { ?>
<div class="pdg"><p class=" t-small">
<?= $post->message ?> <a href="<?= htmlentities($post->href) 
?>">Mehr auf Facebook...</a></p></div><?php } ?>
</div>
<?php }} ?>
</div>
<div class="col pdl">
<?php foreach($this->posts as $post) { if($post->colnum == 1) { ?>
<div class="spacer mgl">
<?php if($post->image !== false) { ?>
<?php if($post->image->type == 'image') { ?>
<div class="postimg">
<a href="<?= htmlentities($post->href) 
?>"><img class="fit" src="<?= $post->image->src 
?>" width="<?= $post->image->width 
?>" height="<?= $post->image->height 
?>" alt="" /></a></div>
<?php } elseif($post->image->type == 'video') { ?>
<div class="postvideo"><?= $post->image->html ?></div>
<?php } ?>
<?php } ?>
<?php if($post->message !== '') { ?>
<div class="pdg"><p class=" t-small">
<?= $post->message ?> <a href="<?= htmlentities($post->href) 
?>">Mehr auf Facebook...</a></p></div><?php } ?>
</div>
<?php }} ?>
</div>
</div>
</div>
<div class="clr noprint pdb"><a title="Folge <?= $this->getField('name') 
?> auf Facebook" href="<?= $this->getField('link') 
?>" class="btn t-medium c-light">Folge <?= $this->getField('name') 
?> auf Facebook</a></div>
</section>
<?php } else { ?>
<section class="wall noprint"><div class="rsp"><p class="t-medium">No posts in the last <?= $this->_cfg->fbDaysBack ?> days.</p></div></section>
<?php }?>

<?= $this->getField('description', '', '<section><div class="rsp ptz"><p class="t-medium">', '</p></div></section>') ?>

<footer>
<?php if($showGoogleMaps) { ?>
<div id="google_maps"></div>
<?php } ?>
<div class="cntr">
<div class="tbl">
<div class="row">
<div class="col rsp vcard" id="hcard">
<div class="t-medium c-light"><a title="<?= $this->getField('name') 
?>" class="url org bold" href="http://<?= str_replace('http://', '', $this->getField('website')) 
?>" rel="bookmark"><?= $this->getField('name') ?></a>
<div class="adr">
<?= $this->getField('street', '', '<span class="street-address">', '</span><br />') 
?> <?= $this->getField('zip', '', '<span class="postal-code">', '</span>') 
?> <?= $this->getField('city', '', '<span class="locality">', '</span>')
?> <?= $this->getField('country', '', '<span class="country-name">', '</span>')
?>
</div>
<div class="pdt">
	<?= $this->getField('phone', '', '<span class="tel"><span class="type">Work</span> <span class="type">Voice</span> T <span class="value" title="', '">') 
	?><?= $this->getField('phone', '', '', '</span></span>') ?>
</div>
</div></div>
<div class="col rsp plr"><div class="t-medium c-light">

<?php $openingTimes = $this->getOpeningTimes(); if(count($openingTimes['time']) > 0){ ?>
<?= $this->_cfg->labels['OpeningTimes'] ?><br />
<?php

$myTimes = array();

foreach ($openingTimes['time'] as $openingTime)
{
	$bits = explode('|', $openingTime);
	$days = explode(', ', $bits[0]);
	
	$time = $bits[1];
	$day = '';
 	
	$i = count($days);
	
	if ($i == 2)
	{
		$day = implode('/', $days);
	}
	elseif ($i > 2)
	{
		$day = array_shift($days);
		$day .= ' - ' . array_pop($days);
	}
	else
	{
		$day = $days[0];
	}
	
	$myTimes[] = str_replace(array(
		'mon',
		'tue',
		'wed',
		'thu',
		'fri',
		'sat',
		'sun'
	), array(
		'Mo',
		'Di',
		'Mi',
		'Do',
		'Fr',
		'Sa',
		'So'
	), $day) . ' ' . str_replace(array(
		':00',
		'-'
	  ), array(
		':00',
		' - '
	  ), $time) . '';
}
?>
<?php foreach($myTimes as $myTime) { ?>
<?= $myTime ?><br />
<?php } ?>
<?php } ?>

</div></div>
</div>
</div>

<?php
if(!empty($this->_cfg->notes['legal'])){
if($legal =  $this->getNote($this->_cfg->notes['legal'], true, true))
{
$legal_subject = $legal->subject;
$legal_message = $legal->message;
?>
<div class="rsp ptz"><p class="t-small c-light"><?= $legal_message ?></p></div>
<?php } ?><?php } else { ?>
<div class="rsp ptz"><p class="t-small c-light">Legal mentions: Add a notice id for notes > legal in jumpage.config.php to display your legal mentions here.</p></div>
<?php } ?>
</div>

<div class="buttons noprint"><a title="Folge <?=  $this->getField('name') 
?> auf Facebook" href="<?= $this->getField('link') 
?>"><img class="ir" src="common/facebook.png" width="48" height="48" alt="Facebook" /></a><a 
title="Hi! I'm a jumpage" href="http://jumpage.net/"><img class="ir"
src="common/jumpage.png" width="48" height="48" alt="jumpage" /></a><div class="topbtn"><a 
href="#top"><img class="ir" src="common/up.png" width="48" height="48" alt="Up" /></a></div></div>
</footer>

<!--
This website was built with jumpage Your web concept - A Bureau BLEEN project
For more information and how to use it, visit jumpage.net
-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

<?php if($showGoogleMaps) { ?>
<script src="//maps.google.com/maps/api/js?sensor=false"></script>
<script>!window.jQuery && document.write(unescape('%3Cscript '
+ 'src="common/jquery-1.8.2.min.js"%3E%3C/script%3E'
)); var googleMapsConfig = [];
googleMapsConfig['Lat'] = <?= floatval($this->getField('latitude')) ?>;
googleMapsConfig['Lng'] = <?= floatval($this->getField('longitude')) ?>;
googleMapsConfig['address'] = '<?= $this->getField('street') . ',' 
	. $this->getField('zip') . ',' . $this->getField('city') ?>';
googleMapsConfig['href'] = '<?= $this->_cfg->googlePlacesLink ?>';
googleMapsConfig['title'] = 'Route planen mit Google Maps...';
googleMapsConfig['zoom'] = 15;
</script>
<?php } ?>

<script src="common/jumpage.js"></script>
<?php if(!empty($this->_cfg->googleAnalyticsWebpropertyId)) { ?>
<script>
var _gaq = [['_setAccount', '<?= $this->_cfg->googleAnalyticsWebpropertyId ?>'], ['_gat._anonymizeIp'], ['_trackPageview']];
(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
<?php } ?>

</body>
</html>